-- 코드를 입력하세요
-- 저자 별, 카테고리 별 매출액(판매량 + 판매가 - BOOK & BOOK_SALES)
-- 저자 ID, 저자명, 카테고리, 매출액(AUTHER, BOOK, SALE는 만들기)
-- 저자 ID 오름차순, 카테고리 내림차순
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B2.CATEGORY, B2.TOTAL_SALES
FROM AUTHOR AS A
JOIN(SELECT B.AUTHOR_ID, B.CATEGORY, SUM(B.PRICE * BS.SALES) AS TOTAL_SALES
    FROM BOOK AS B
    JOIN (SELECT BOOK_ID, SUM(SALES) as SALES FROM BOOK_SALES
          WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
          GROUP BY BOOK_ID) AS BS
    ON B.BOOK_ID = BS.BOOK_ID
    GROUP BY AUTHOR_ID, CATEGORY) as B2
ON A.AUTHOR_ID = B2.AUTHOR_ID
ORDER BY A.AUTHOR_ID ASC, B2.CATEGORY DESC;