-- 코드를 입력하세요
-- 2022/05 식품들의 PRODUCT_ID, PRODUCT_NAME, TOTAL_SALES(총매출)
-- 총매출 기준 내림차순 정렬 / 식품ID 기준 오름차순 정렬

-- (1)2022/05 식품들 추려내서 총매출 테이블 구하기
-- (2)총메출 테이블과 조인하여 PRODUCT_ID, PRODUCT_NAME, TOTAL_SALES
-- (3)정렬
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, (FP.PRICE * FO.TOTAL) AS TOTAL_SALES
FROM FOOD_PRODUCT AS FP
JOIN (SELECT PRODUCT_ID, ORDER_ID, SUM(AMOUNT) AS TOTAL
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
    GROUP BY PRODUCT_ID) AS FO
ON FP.PRODUCT_ID = FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID ASC